version: '3'

services:
  http-server:
    container_name: http-prometheus-server
    build:
      context: ..
    ports:
      - 8080:8080
  prometheus:
    container_name: prometheus
    hostname: prometheus
    image: prom/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    ports:
      - 9090:9090

  grafana:
    container_name: grafana
    hostname: grafana
    image: grafana/grafana
    volumes:
      - ./grafana/config.ini:/etc/grafana/grafana.ini
      - ./grafana/datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml
      - ./grafana/dashboard.yaml:/etc/grafana/provisioning/dashboards/dashboard.yaml
      - ./grafana/dashboards:/etc/dashboards
      - grafana_data:/var/lib/grafana
    ports:
      - 3000:3000

volumes:
  prometheus_data: {}
  grafana_data: {}
